#!/bin/sh

case $BLOCK_BUTTON in
  3) pactl set-sink-mute 1 toggle ;; # middle click
  4) sh -c "pactl set-sink-mute 1 false; pactl set-sink-volume 1 +5%" ;; # scroll up
  5) sh -c "pactl set-sink-mute 1 false; pactl set-sink-volume 1 -5%" ;; # scroll down
esac

echo VOL
